version: '3.8'

services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
